version: "3"

services:
  api_sanic:
    build:
      context: .
      dockerfile: ./docker/api_sanic_docker/Dockerfile
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      MONGO_HOST: mongodb
    networks:
      - sanic_net
  
  consumer_sanic:
    build:
      context: .
      dockerfile: ./docker/consumer_sanic_docker/Dockerfile
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      MONGO_HOST: mongodb
    networks:
      - sanic_net

  nginx:
    image: nginx:1.13.6-alpine
    ports:
      - "81:80"
    depends_on:
      - api_sanic
      - consumer_sanic
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    networks:
      - sanic_net
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    hostname: rabbitmq
    ports:
        - 5673:5672
        - 15673:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - sanic_net
  
  mongodb:
    image: mongo
    container_name: 'mongo'
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ~/apps/mongo:/data/db
    networks:
      - sanic_net

networks:
  sanic_net:
    driver: bridge
